//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDetail
    {
        public int ID { get; set; }
        public string RoleDetailID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IDRole { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
